# Generated by Django 4.2.4 on 2023-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("data", models.TextField(verbose_name="About ")),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("is_liked", models.BooleanField(default=False)),
                ("user_id", models.BigIntegerField()),
            ],
        ),
    ]
