# Generated by Django 4.1 on 2024-03-17 07:49

from django.conf import settings
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                (
                    "data",
                    models.TextField(blank=True, null=True, verbose_name="About "),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=events.models.upload_to
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "is_liked",
                    models.ManyToManyField(
                        related_name="liked_events", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
