# Generated by Django 4.1 on 2024-03-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_image_remove_event_user_id_event_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="user_id",
        ),
        migrations.AddField(
            model_name="event",
            name="user_id",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
