# Generated by Django 4.1 on 2024-03-16 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0004_alter_event_data_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="users",
            field=models.ManyToManyField(
                related_name="events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
